---
- name: Get facts from nodes
  hosts: all

  tasks:
    - name: Get facts with NAPALM
      napalm_get_facts:
        hostname: "{{ansible_host}}"
        username: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        dev_os: "{{ansible_network_os}}"
