---
- name: Push configuration
  hosts: all
  tasks:
  - name: Push configuration with NAPALM
    napalm_install_config:
        hostname: "{{ansible_host}}"
        username: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        dev_os: "{{ansible_network_os}}"
        config_file: "config/{{ansible_host}}/00_fullconf.txt"
        diff_file: "config/{{ansible_host}}/diff"
        commit_changes: true
